import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import {
  INITIAL_CATEGORIES,
  INITIAL_PRODUCTS,
  INITIAL_COMPETITORS,
  INITIAL_COMPETITOR_PRODUCTS,
  INITIAL_COMPETITOR_PRICE_SNAPSHOTS,
  INITIAL_BUSINESS_RULES,
  INITIAL_SALES_TRANSACTIONS,
  INITIAL_AUDIT_LOGS,
  INITIAL_NOTIFICATIONS,
  INITIAL_RECOMMENDATIONS
} from '../lib/seedData';

// Read environment variables from .env.local
const envPath = path.join(process.cwd(), '.env.local');
let supabaseUrl = '';
let supabaseAnonKey = '';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const lines = envContent.split('\n');
  for (const line of lines) {
    const parts = line.split('=');
    if (parts.length >= 2) {
      const key = parts[0].trim();
      const val = parts.slice(1).join('=').trim();
      if (key === 'NEXT_PUBLIC_SUPABASE_URL') supabaseUrl = val;
      if (key === 'NEXT_PUBLIC_SUPABASE_ANON_KEY') supabaseAnonKey = val;
    }
  }
}

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Error: NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY is missing from .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seed() {
  console.log('Connecting to Supabase at:', supabaseUrl);

  try {
    // 1. Delete existing records in child-to-parent order to avoid foreign key violations
    console.log('Cleaning up existing database records...');
    
    await supabase.from('notifications').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('audit_logs').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('sales_transactions').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('price_recommendations').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('business_rules').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('competitor_price_snapshots').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('competitor_products').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('competitors').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('products').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('categories').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    
    console.log('Cleanup completed.');

    // 2. Insert Categories (Letting ID autogenerate)
    console.log('Seeding categories...');
    const { data: seededCats, error: catErr } = await supabase.from('categories').insert(
      INITIAL_CATEGORIES.map(c => ({
        name: c.name,
        description: c.description
      }))
    ).select();
    
    if (catErr) throw catErr;
    console.log('Categories seeded.');

    // Map initial category ID to autogenerated database UUID
    const categoryMap: Record<string, string> = {};
    INITIAL_CATEGORIES.forEach(c => {
      const dbCat = seededCats.find(dc => dc.name === c.name);
      if (dbCat) {
        categoryMap[c.id] = dbCat.id;
      }
    });

    // 3. Insert Products
    console.log('Seeding products...');
    const { data: seededProds, error: prodErr } = await supabase.from('products').insert(
      INITIAL_PRODUCTS.map(p => ({
        sku: p.sku,
        name: p.name,
        category_id: categoryMap[p.categoryId] || null,
        brand: p.brand,
        cost_price: p.costPrice,
        current_price: p.currentPrice,
        min_price: p.minPrice,
        max_price: p.maxPrice,
        target_margin: p.targetMargin,
        inventory: p.inventory,
        seasonal_relevance: p.seasonalRelevance,
        status: p.status,
        created_at: p.createdAt,
        updated_at: p.updatedAt
      }))
    ).select();
    
    if (prodErr) throw prodErr;
    console.log('Products seeded.');

    // Map initial product ID to autogenerated database UUID
    const productMap: Record<string, string> = {};
    INITIAL_PRODUCTS.forEach(p => {
      const dbProd = seededProds.find(dp => dp.sku === p.sku);
      if (dbProd) {
        productMap[p.id] = dbProd.id;
      }
    });

    // 4. Insert Competitors
    console.log('Seeding competitors...');
    const { data: seededComps, error: compErr } = await supabase.from('competitors').insert(
      INITIAL_COMPETITORS.map(c => ({
        name: c.name,
        website: c.website
      }))
    ).select();
    
    if (compErr) throw compErr;
    console.log('Competitors seeded.');

    // Map initial competitor ID to database UUID
    const competitorMap: Record<string, string> = {};
    INITIAL_COMPETITORS.forEach(c => {
      const dbComp = seededComps.find(dc => dc.name === c.name);
      if (dbComp) {
        competitorMap[c.id] = dbComp.id;
      }
    });

    // 5. Insert Competitor Products
    console.log('Seeding competitor products...');
    const competitorProductsData = INITIAL_COMPETITOR_PRODUCTS.map(cp => ({
      product_id: productMap[cp.productId],
      competitor_id: competitorMap[cp.competitorId],
      competitor_sku: cp.competitorSku,
      url: cp.url
    })).filter(cp => cp.product_id && cp.competitor_id);

    const { data: seededCompProds, error: compProdErr } = await supabase.from('competitor_products').insert(
      competitorProductsData
    ).select();
    
    if (compProdErr) throw compProdErr;
    console.log('Competitor products seeded.');

    // Map competitor product mapping ID
    const competitorProductMap: Record<string, string> = {};
    INITIAL_COMPETITOR_PRODUCTS.forEach(cp => {
      const mappedProductId = productMap[cp.productId];
      const mappedCompetitorId = competitorMap[cp.competitorId];
      const dbCompProd = seededCompProds.find(dcp => 
        dcp.product_id === mappedProductId && 
        dcp.competitor_id === mappedCompetitorId
      );
      if (dbCompProd) {
        competitorProductMap[cp.id] = dbCompProd.id;
      }
    });

    // 6. Insert Competitor Price Snapshots
    console.log('Seeding competitor price snapshots...');
    const snapshotData = INITIAL_COMPETITOR_PRICE_SNAPSHOTS.map(cps => ({
      competitor_product_id: competitorProductMap[cps.competitorProductId],
      price: cps.price,
      recorded_at: cps.recordedAt
    })).filter(cps => cps.competitor_product_id);

    const { error: snapErr } = await supabase.from('competitor_price_snapshots').insert(snapshotData);
    if (snapErr) throw snapErr;
    console.log('Price snapshots seeded.');

    // 7. Insert Business Rules
    console.log('Seeding business rules...');
    const { error: ruleErr } = await supabase.from('business_rules').insert(
      INITIAL_BUSINESS_RULES.map(r => ({
        name: r.name,
        code: r.code,
        type: r.type,
        parameters: r.parameters,
        is_active: r.isActive,
        updated_at: r.updatedAt
      }))
    );
    if (ruleErr) throw ruleErr;
    console.log('Business rules seeded.');

    // 8. Insert Sales Transactions
    console.log('Seeding sales transactions...');
    const txData = INITIAL_SALES_TRANSACTIONS.map(t => ({
      product_id: productMap[t.productId],
      quantity: t.quantity,
      price_sold: t.priceSold,
      revenue: t.revenue,
      transaction_date: t.transactionDate
    })).filter(t => t.product_id);

    const { error: txErr } = await supabase.from('sales_transactions').insert(txData);
    if (txErr) throw txErr;
    console.log('Sales transactions seeded.');

    // 9. Insert Price Recommendations
    console.log('Seeding price recommendations...');
    const recData = INITIAL_RECOMMENDATIONS.map(r => ({
      product_id: productMap[r.productId],
      suggested_price: r.suggestedPrice,
      min_suggested_price: r.minSuggestedPrice,
      max_suggested_price: r.maxSuggestedPrice,
      predicted_demand: r.predictedDemand,
      confidence_score: r.confidenceScore,
      margin_estimate: r.marginEstimate,
      revenue_estimate: r.revenueEstimate,
      explanation: r.explanation,
      status: r.status,
      created_at: r.createdAt
    })).filter(r => r.product_id);

    const { error: recErr } = await supabase.from('price_recommendations').insert(recData);
    if (recErr) throw recErr;
    console.log('Price recommendations seeded.');

    // 10. Insert Audit Logs
    console.log('Seeding audit logs...');
    const { error: logErr } = await supabase.from('audit_logs').insert(
      INITIAL_AUDIT_LOGS.map(l => ({
        user_email: l.userEmail,
        action: l.action,
        details: l.details,
        timestamp: l.timestamp
      }))
    );
    if (logErr) throw logErr;
    console.log('Audit logs seeded.');

    // 11. Insert Notifications
    console.log('Seeding notifications...');
    const { error: notifErr } = await supabase.from('notifications').insert(
      INITIAL_NOTIFICATIONS.map(n => ({
        title: n.title,
        message: n.message,
        type: n.type,
        is_read: n.isRead,
        created_at: n.createdAt
      }))
    );
    if (notifErr) throw notifErr;
    console.log('Notifications seeded.');

    console.log('\n=========================================');
    console.log('Database seeded successfully with all sandbox records (autogenerated UUIDs mapped correctly)!');
    console.log('=========================================');

  } catch (error: any) {
    console.error('Seeding process failed with error:', error.message || error);
    process.exit(1);
  }
}

seed();
